### ISSUE TITLE
Issues with space

### ISSUE THREAD

**Issue by mxmilkiib** [chetan51/deadmouse#1]
I reply heavily on using space to page down. Deadmouse disabled this which isn't handy. I understand that some links have spaces, but maybe if the first key hit is space then it should do a page down rather than start to select a link.

(Hitting space multiple times seems to give strange selections anyway; on the GH commenting page; 'Issues', 'Pull Requests' then 'Gist' are selected. If i start with 'co' to get Code, then hit space, I then get 'Help', 'Gist', then 'Explore').

Thanks!

**Comment by chetan51** [comment]
Fixed in latest update (v1.7).
