### ISSUE TITLE
repackage as a website plugin

### ISSUE THREAD

**Issue by deanrather** [chetan51/deadmouse#5]
I would like to include this on my website (much like you do on http://chetan51.github.com/deadmouse/)

I can see your source code and copy the relevant files out of there and patch it back together myself -- but it would be nice if you could package it (perhaps in a seperate branch) as a plugin for inclusion on websites!

Thanks,
Dean.

**Comment by chetan51** [comment]
I'm just curious: why do you want to include this on your website?

**Comment by deanrather** [comment]
So that my website can be "keyboard friendly" :)

**Comment by chetan51** [comment]
You can just include the following tags on your page:

```
<link rel="stylesheet" href="http://chetan51.github.com/deadmouse/stylesheets/main.css">
<script src="http://chetan51.github.com/deadmouse/javascripts/zepto.min.js"></script>
<script src="http://chetan51.github.com/deadmouse/javascripts/string_score.js"></script>
<script src="http://chetan51.github.com/deadmouse/javascripts/hook.js"></script>
```

**Comment by deanrather** [comment]
cool beans.
